#!/usr/bin/env bash
# This stand-alone script should be able to be used to kickstart a new node

PROJECT_ROOT=/opt/puppet
ROLE=st2express

# Install Pre-req for git
if [ -f /usr/bin/apt-get ]; then
  apt-get install -y git
fi

if [ -f /usr/bin/yum ]; then
  yum install -y git-core
fi

if [ ! -d ${PROJECT_ROOT}/.git ]; then
  # Backup the directory in the event that masterless setup goes south
  if [ -d ${PROJECT_ROOT} ]; then
    mv ${PROJECT_ROOT} ${PROJECT_ROOT}.old
  fi
  git clone https://github.com/StackStorm/st2workroom ${PROJECT_ROOT}
fi

# Ability to disable hubot, drop to long-term setting for installer.
if [ -n "$DISABLE_HUBOT" ]; then
  echo "hubot: false" >> ${PROJECT_ROOT}/hieradata/workroom.yaml
fi

# Create Facter sink
if [ ! -d /etc/facter/facts.d ]; then
  echo "Setting up facter.d..."
  mkdir -p /etc/facter/facts.d
fi

if [ -n "$CI" ]; then
  # The st2express_ci role is identical in nature in that
  # it inherits 100% the st2express role. It only differs
  # so that we can set CI specific environment variables
  # to run tests properly.
  #
  # ENV is also exported to cut down on the build time
  # by using only what is cloned.
  ROLE=st2express_ci
  export ENV="current_working_directory"
fi

echo "role=${ROLE}" > /etc/facter/facts.d/role.txt

# Start up the st2express bootstrap
${PROJECT_ROOT}/script/bootstrap-os

# Converge the system
${PROJECT_ROOT}/script/puppet-apply

# Check to see if StackStorm is running properly
if [ -n "$SKIP_OK_CHECK" ]; then
  ${PROJECT_ROOT}/script/check-st2-ok
fi
